# Generated by Django 5.0.4 on 2024-04-10 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 10)),
            preserve_default=False,
        ),
    ]
