# Generated by Django 5.0.4 on 2024-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_alter_activity_options_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reminder_completed',
            field=models.BooleanField(default=False),
        ),
    ]
