# Generated by Django 5.0.4 on 2024-04-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_activity_reminder_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Activities'},
        ),
    ]
