# Generated by Django 5.0.4 on 2024-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_application_company_interview_jobposting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Response pending', 'Response pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Response pending', max_length=20),
        ),
    ]
