# Generated by Django 5.0.4 on 2024-04-07 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Starting time')),
                ('end_time', models.TimeField(verbose_name='Ending time')),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Break', 'Break'), ('Job search', 'Job search'), ('Leisure', 'Leisure'), ('Vacation', 'Vacation'), ('Illness', 'Illness'), ('Other', 'Other')], default='Work', max_length=20)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
